name: pharmacy
description: A new Flutter project.


publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  flutter_svg: ^1.0.3
  cached_network_image: ^3.2.0
  http: ^0.13.4
  rxdart: ^0.27.3
  sqflite: ^2.0.2


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0


flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/icons/menu/
    - assets/icons/favorite/
    - assets/icons/bin/
  fonts:
     - family: Roboto
       fonts:
         - asset: assets/fonts/Roboto-Medium.ttf
           weight: 500
         - asset: assets/fonts/Roboto-Regular.ttf
           weight: 400
         - asset: assets/fonts/Roboto-Thin.ttf
           weight: 300
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
